name: Publish on NPM

on:
  release:
    types:
      - published

permissions:
  id-token: write # Required to work with trusted publishers (OIDC)
  contents: read

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm # Default cache directory for npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm run release
