name: Release

on:
  milestone:
    types:
      - closed

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm # Default cache directory for npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: |
          git reset --hard
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          npm run release
